# Generated by Django 4.1.7 on 2023-04-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('filter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.filter')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
            options={
                'db_table': 'item_filter',
            },
        ),
    ]
