# Generated by Django 4.1.7 on 2023-06-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_faq'),
        ('user', '0002_mailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferredCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'preferred_categories',
                'db_table': 'preferred_category',
            },
        ),
    ]
