# Generated by Django 4.1.7 on 2023-06-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userreport',
            table='user_report',
        ),
    ]
