# Generated by Django 4.1.7 on 2023-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userreport_tableasdas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
